### ISSUE TITLE
Needing help getting a UDF Filesystem Driver to work

### ISSUE THREAD

**Issue by Zero3K** [pali/udftools#61] opened 2023-02-24 13:16 UTC
I am having a guy work on it. Right now, he is stuck on getting it to recognize the AVDP that Windows 7/10/Linux includes when formatting a Hard Disk as it. The driver's source code is at https://github.com/reactos/reactos/tree/master/drivers/filesystems/udfs.

**Comment by pali** [comment] 2023-02-26 08:11
Sorry but I do not understand. You you write more precisely which tool from udftools project has issue and how to reproduce it?

**Comment by Zero3K** [comment] 2023-02-26 14:33
Never mind, I have found another developer to help him get it working, etc.

**Comment by Zero3K** [comment] 2023-02-28 23:01
It is an issue with a driver made for ReactOS/Windows Server 2003 and up. Not an issue with UDFTools.

**Comment by Zero3K** [comment] 2023-03-01 01:02
I sent you a request to join as a co-worker.

**Comment by Zero3K** [comment] 2023-03-04 02:30
Will you accept it or not?

**Comment by Zero3K** [comment] 2023-03-25 13:41
Please answer the questions that he commented to this issue:

https://github.com/Zero3K/udfs/issues/1

**Comment by pali** [comment] 2023-03-25 13:45
Sorry, but I absolutely do not understand your issue. Please describe more precisely what you are observing. Does not some of the udftools work on disk created/modified by your made driver? Or what?

**Comment by Zero3K** [comment] 2023-03-25 13:48
I just want to see if you can help answer his questions so the UDFS driver used by ReactOS can be made to work properly. I tried using the formatting program to make a UDF 2.01 drive. The driver is able to mount it and show its contents, but after a reboot, the drive is corrupted by the driver.

**Comment by pali** [comment] 2023-03-25 13:51
Sorry, but you still have not described any issue. I really do not know what should I answer or comment. If there is no reported information for udftools, I'm going to close this issue.

**Comment by Zero3K** [comment] 2023-03-25 13:57
Oh, so you only deal with udftools and are not willing to share your knowledge with another developer.

**Comment by pali** [comment] 2023-03-25 14:00
Sorry, my crystal ball is broken and because you refused to describe what is the issue or question even after repeated attempts, I have no other option how to figure out what is is going here.

**Closed as completed by pali** 2023-03-25 14:00 UTC

**Comment by Zero3K** [comment] 2023-03-25 14:03
"Here is the log file: I would like confirmation that the overwriting is not in my head lol. Location in question is under UDFBuildFreeSpaceBitmap where we have multiple Extents that are found at different lba logical the one i am worried about is 0x1b0. Later we are Setting up tags for Root directory EFE along with other FE but the root directory EFE is located at logical lba 0x1a0. Which is what leads me to believe that the Extent at 1b0 is getting overwritten which in turn is calculating the incorrect CRC. But that is my opinion, and a lot happens to the same logical lba so I would love to get your opinion as well. @Alter-1
Edit 1: Also unsure if the correct LastPossibleLba is set correctly or it needs to be converted to logical, because under UDFPartLbaToPhys we use it to check that the logical LBA calculated is not out of bounds which it is for some unalloc_space_desc which I resolved by not allowing it to check if it is out of bounds or not."

[udf (1).log](https://github.com/pali/udftools/files/11069073/udf.1.log)

**Comment by Zero3K** [comment] 2023-03-25 14:11
Or you can join the chatroom that he and I are in.
